<?php

use Symfony\Component\HttpFoundation\RedirectResponse;

/*
 * The following content was designed & implemented under AlexSeif.com
 * https://drupal.stackexchange.com/questions/257650/multilingual-article-should-display-404-when-a-translation-is-not-available
 */

function translation404_entity_view(array &$build, \Drupal\Core\Entity\EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display, $view_mode)
{
  $lang = \Drupal::languageManager()->getCurrentLanguage()->getId();
  $lang = ($lang == "en") ? "" : $lang;
  $ent_lang = $entity->langcode->value;
  if ($view_mode == "full" && $lang != $ent_lang) {
    $response = new RedirectResponse("/$lang");
    drupal_set_message(t('Page not found.'));
    $response->send();
    return;
//    throw new \Symfony\Component\HttpKernel\Exception\NotFoundHttpException();
  }
}
